version: '3.9'

services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - $OLM_FOLDER:/var/www
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    links:
      - olm

  olm:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        OLM_FOLDER: "${OLM_FOLDER}"
    volumes:
      - $OLM_FOLDER:/var/www
      - ./scripts/internal:/scripts:ro
    env_file: .env

  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
    env_file: .env
