FROM php:7.3-fpm-alpine

ARG OLM_FOLDER=''
WORKDIR /var/www

## install composer
RUN apk add nodejs-current npm libpng libpng-dev libzip-dev mysql-client && \
    docker-php-ext-install -j$(nproc) gd pcntl zip pdo pdo_mysql && \
    php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');" && \
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer --version=2.4.2

RUN addgroup -S olm && adduser -S olm -G olm
USER olm
